### ISSUE TITLE
老师傅对nc6x的代码研究如何哇，请教一个问题

### ISSUE THREAD

**Issue by ghost** [airh2o/idea_plugin_nc5devplugin#18]
最近在研究nc的portal用户密码加解密方式，但是没有着手出，比如sm_user中数据库存储的密码都是 U_U++--V281415b277b1ec75bfe787830caf6ad9 这种格式，在哪里去寻找加密方式呢？以及如何尝试解密呢

**Comment by airh2o** [comment]
不能反编译。
