### ISSUE TITLE
支持bip 2207？

### ISSUE THREAD

**Issue by gamerenzz** [airh2o/idea_plugin_nc5devplugin#19]
请问后续能支持 bip 2207？

**Comment by airh2o** [comment]
我手里目前没有2207的HOME和演示数据，你可以分享给一下 我适配下

**Comment by airh2o** [comment]
> 请问后续能支持 bip 2207？
我手里目前没有2207的HOME和演示数据，你可以分享给一下 我适配下， 只要我会做到的版本 我都会适配。

**Comment by gamerenzz** [comment]
YONbip V3
链接：https://pan.baidu.com/s/1UmAuOwFR9ahFMMXqGObX0g 
提取码：oy6u

**Comment by gamerenzz** [comment]
2207的，有空的时候，看看

**Comment by airh2o** [comment]
> 2207的，有空的时候，看看

OK

**Comment by gamerenzz** [comment]
> > 2207的，有空的时候，看看
> 
> OK

老师，请问有单独的把 导出的 patch补丁，转换为zip的工具？

您的工具比较适合懂开发的那种高人，像我们这种小白用起来比较深奥。

**Comment by airh2o** [comment]
就是NCC的新版本，改了个名字而已， 支持。

**Comment by zhangwxi** [comment]
有YONbip V3前端源代码吗 想好好学习学习 谢谢
